export const imagesWorks = [
  {
    id: "500px-Ada_Kaleh_Vár",
    url: "https://ritadavis.com.br/images/500px-Ada_Kaleh_Vár.jpg",
    title: "Ada Kaleh",
    project: "ada_kaleh",
    description: "",
  },

  {
    id: "ada-01",
    url: "https://ritadavis.com.br/images/ada-01.jpg",
    title: "Ada",
    project: "ada",
    description: "",
  },
  {
    id: "ada-02",
    url: "https://ritadavis.com.br/images/ada-02.jpg",
    title: "Ada",
    project: "ada",
    description: "",
  },
  {
    id: "ada-03",
    url: "https://ritadavis.com.br/images/ada-03.jpg",
    title: "Ada",
    project: "ada",
    description: "",
  },
  {
    id: "ada-04",
    url: "https://ritadavis.com.br/images/ada-04.jpg",
    title: "Ada",
    project: "ada",
    description: "",
  },

  {
    id: "anel-01",
    url: "https://ritadavis.com.br/images/anel-01.jpg",
    title: "Anel",
    project: "anel",
    description: "",
  },

  {
    id: "boi-01",
    url: "https://ritadavis.com.br/images/boi-01.jpg",
    title: "Boi",
    project: "boi",
    description: "",
  },
  {
    id: "boi-02",
    url: "https://ritadavis.com.br/images/boi-02.jpg",
    title: "Boi",
    project: "boi",
    description: "",
  },
  {
    id: "boi-03",
    url: "https://ritadavis.com.br/images/boi-03.jpg",
    title: "Boi",
    project: "boi",
    description: "",
  },
  {
    id: "boi-04",
    url: "https://ritadavis.com.br/images/boi-04.jpg",
    title: "Boi",
    project: "boi",
    description: "",
  },

  {
    id: "cabare-01",
    url: "https://ritadavis.com.br/images/cabare-01.jpg",
    title: "Cabare",
    project: "cabare",
    description: "",
  },
  {
    id: "cabare-02",
    url: "https://ritadavis.com.br/images/cabare-02.jpg",
    title: "Cabare",
    project: "cabare",
    description: "",
  },
  {
    id: "cabare-03",
    url: "https://ritadavis.com.br/images/cabare-03.jpg",
    title: "Cabare",
    project: "cabare",
    description: "",
  },
  {
    id: "cabare-04",
    url: "https://ritadavis.com.br/images/cabare-04.jpg",
    title: "Cabare",
    project: "cabare",
    description: "",
  },

  {
    id: "cegueira-01",
    url: "https://ritadavis.com.br/images/cegueira-01.jpg",
    title: "Cegueira",
    project: "cegueira",
    description: "",
  },
  {
    id: "cegueira-02",
    url: "https://ritadavis.com.br/images/cegueira-02.jpg",
    title: "Cegueira",
    project: "cegueira",
    description: "",
  },
  {
    id: "cegueira-03",
    url: "https://ritadavis.com.br/images/cegueira-03.jpg",
    title: "Cegueira",
    project: "cegueira",
    description: "",
  },
  {
    id: "cegueira-04",
    url: "https://ritadavis.com.br/images/cegueira-04.jpg",
    title: "Cegueira",
    project: "cegueira",
    description: "",
  },

  {
    id: "cidade-01",
    url: "https://ritadavis.com.br/images/cidade-01.jpg",
    title: "Cidade",
    project: "cidade",
    description: "",
  },
  {
    id: "cidade-02",
    url: "https://ritadavis.com.br/images/cidade-02.jpg",
    title: "Cidade",
    project: "cidade",
    description: "",
  },
  {
    id: "cidade-03",
    url: "https://ritadavis.com.br/images/cidade-03.jpg",
    title: "Cidade",
    project: "cidade",
    description: "",
  },

  {
    id: "circo-01",
    url: "https://ritadavis.com.br/images/circo-01.jpg",
    title: "Circo",
    project: "circo",
    description: "",
  },
  {
    id: "circo-02",
    url: "https://ritadavis.com.br/images/circo-02.jpg",
    title: "Circo",
    project: "circo",
    description: "",
  },
  {
    id: "circo-03",
    url: "https://ritadavis.com.br/images/circo-03.jpg",
    title: "Circo",
    project: "circo",
    description: "",
  },
  {
    id: "circo-04",
    url: "https://ritadavis.com.br/images/circo-04.jpg",
    title: "Circo",
    project: "circo",
    description: "",
  },

  {
    id: "coisas-01",
    url: "https://ritadavis.com.br/images/coisas-01.jpg",
    title: "Coisas",
    project: "coisas",
    description: "",
  },
  {
    id: "coisas-02",
    url: "https://ritadavis.com.br/images/coisas-02.jpg",
    title: "Coisas",
    project: "coisas",
    description: "",
  },
  {
    id: "coisas-03",
    url: "https://ritadavis.com.br/images/coisas-03.jpg",
    title: "Coisas",
    project: "coisas",
    description: "",
  },

  {
    id: "couch-01",
    url: "https://ritadavis.com.br/images/couch-01.jpg",
    title: "Couch",
    project: "couch",
    description: "",
  },
  {
    id: "couch-02",
    url: "https://ritadavis.com.br/images/couch-02.jpg",
    title: "Couch",
    project: "couch",
    description: "",
  },
  {
    id: "couch-03",
    url: "https://ritadavis.com.br/images/couch-03.jpg",
    title: "Couch",
    project: "couch",
    description: "",
  },

  {
    id: "craft-01",
    url: "https://ritadavis.com.br/images/craft-01.jpg",
    title: "Craft",
    project: "craft",
    description: "",
  },
  {
    id: "craft-02",
    url: "https://ritadavis.com.br/images/craft-02.jpg",
    title: "Craft",
    project: "craft",
    description: "",
  },
  {
    id: "craft-03",
    url: "https://ritadavis.com.br/images/craft-03.jpg",
    title: "Craft",
    project: "craft",
    description: "",
  },
  {
    id: "craft-04",
    url: "https://ritadavis.com.br/images/craft-04.jpg",
    title: "Craft",
    project: "craft",
    description: "",
  },

  {
    id: "drama-01",
    url: "https://ritadavis.com.br/images/drama-01.jpg",
    title: "Drama",
    project: "drama",
    description: "",
  },
  {
    id: "drama-02",
    url: "https://ritadavis.com.br/images/drama-02.jpg",
    title: "Drama",
    project: "drama",
    description: "",
  },
  {
    id: "drama-03",
    url: "https://ritadavis.com.br/images/drama-03.jpg",
    title: "Drama",
    project: "drama",
    description: "",
  },
  {
    id: "drama-04",
    url: "https://ritadavis.com.br/images/drama-04.jpg",
    title: "Drama",
    project: "drama",
    description: "",
  },
  {
    id: "drama-05",
    url: "https://ritadavis.com.br/images/drama-05.jpg",
    title: "Drama",
    project: "drama",
    description: "",
  },

  {
    id: "escuta-01",
    url: "https://ritadavis.com.br/images/escuta-01.jpg",
    title: "Escuta",
    project: "escuta",
    description: "",
  },
  {
    id: "escuta-02",
    url: "https://ritadavis.com.br/images/escuta-02.jpg",
    title: "Escuta",
    project: "escuta",
    description: "",
  },
  {
    id: "escuta-03",
    url: "https://ritadavis.com.br/images/escuta-03.jpg",
    title: "Escuta",
    project: "escuta",
    description: "",
  },
  {
    id: "escuta-04",
    url: "https://ritadavis.com.br/images/escuta-04.jpg",
    title: "Escuta",
    project: "escuta",
    description: "",
  },

  {
    id: "febre-01",
    url: "https://ritadavis.com.br/images/febre-01.jpg",
    title: "Febre",
    project: "febre",
    description: "",
  },

  {
    id: "fingers-01",
    url: "https://ritadavis.com.br/images/fingers-01.png",
    title: "Fingers",
    project: "fingers",
    description: "",
  },
  {
    id: "fingers-02",
    url: "https://ritadavis.com.br/images/fingers-02.png",
    title: "Fingers",
    project: "fingers",
    description: "",
  },
  {
    id: "fingers-03",
    url: "https://ritadavis.com.br/images/fingers-03.jpg",
    title: "Fingers",
    project: "fingers",
    description: "",
  },
  {
    id: "fingers-04",
    url: "https://ritadavis.com.br/images/fingers-04.jpg",
    title: "Fingers",
    project: "fingers",
    description: "",
  },

  {
    id: "flopi-01",
    url: "https://ritadavis.com.br/images/flopi-01.jpg",
    title: "Flopi",
    project: "flopi",
    description: "",
  },
  {
    id: "flopi-02",
    url: "https://ritadavis.com.br/images/flopi-02.jpg",
    title: "Flopi",
    project: "flopi",
    description: "",
  },
  {
    id: "flopi-03",
    url: "https://ritadavis.com.br/images/flopi-03.jpg",
    title: "Flopi",
    project: "flopi",
    description: "",
  },

  {
    id: "gift-01",
    url: "https://ritadavis.com.br/images/gift-01.jpg",
    title: "Gift",
    project: "gift",
    description: "",
  },
  {
    id: "gift-02",
    url: "https://ritadavis.com.br/images/gift-02.jpg",
    title: "Gift",
    project: "gift",
    description: "",
  },
  {
    id: "gift-03",
    url: "https://ritadavis.com.br/images/gift-03.jpg",
    title: "Gift",
    project: "gift",
    description: "",
  },
  {
    id: "gift-04",
    url: "https://ritadavis.com.br/images/gift-04.jpg",
    title: "Gift",
    project: "gift",
    description: "",
  },

  {
    id: "gratifica-01",
    url: "https://ritadavis.com.br/images/gratifica-01.jpg",
    title: "Gratifica",
    project: "gratifica",
    description: "",
  },
  {
    id: "gratifica-02",
    url: "https://ritadavis.com.br/images/gratifica-02.jpg",
    title: "Gratifica",
    project: "gratifica",
    description: "",
  },
  {
    id: "gratifica-03",
    url: "https://ritadavis.com.br/images/gratifica-03.jpg",
    title: "Gratifica",
    project: "gratifica",
    description: "",
  },
  {
    id: "gratifica-04",
    url: "https://ritadavis.com.br/images/gratifica-04.jpg",
    title: "Gratifica",
    project: "gratifica",
    description: "",
  },

  {
    id: "heart-01",
    url: "https://ritadavis.com.br/images/heart-01.jpg",
    title: "Heart",
    project: "heart",
    description: "",
  },
  {
    id: "horses-01",
    url: "https://ritadavis.com.br/images/horses-01.jpg",
    title: "Horses",
    project: "horses",
    description: "",
  },
  {
    id: "inferninho-01",
    url: "https://ritadavis.com.br/images/inferninho-01.jpg",
    title: "Inferninho",
    project: "inferninho",
    description: "",
  },

  {
    id: "joints-01",
    url: "https://ritadavis.com.br/images/joints-01.jpg",
    title: "Joints",
    project: "joints",
    description: "",
  },
  {
    id: "joints-02",
    url: "https://ritadavis.com.br/images/joints-02.jpeg",
    title: "Joints",
    project: "joints",
    description: "",
  },
  {
    id: "joints-03",
    url: "https://ritadavis.com.br/images/joints-03.jpeg",
    title: "Joints",
    project: "joints",
    description: "",
  },
  {
    id: "joints-04",
    url: "https://ritadavis.com.br/images/joints-04.jpg",
    title: "Joints",
    project: "joints",
    description: "",
  },

  {
    id: "katarina-01",
    url: "https://ritadavis.com.br/images/katarina-01.jpg",
    title: "Katarina",
    project: "katarina",
    description: "",
  },

  {
    id: "leonilson-01",
    url: "https://ritadavis.com.br/images/leonilson-01.jpg",
    title: "Leonilson",
    project: "leonilson",
    description: "",
  },
  {
    id: "leonilson-02",
    url: "https://ritadavis.com.br/images/leonilson-02.jpg",
    title: "Leonilson",
    project: "leonilson",
    description: "",
  },
  {
    id: "leonilson-03",
    url: "https://ritadavis.com.br/images/leonilson-03.jpg",
    title: "Leonilson",
    project: "leonilson",
    description: "",
  },
  {
    id: "leonilson-04",
    url: "https://ritadavis.com.br/images/leonilson-04.jpg",
    title: "Leonilson",
    project: "leonilson",
    description: "",
  },

  {
    id: "printas-01",
    url: "https://ritadavis.com.br/images/printas-01.jpg",
    title: "Printas",
    project: "printas",
    description: "",
  },
  {
    id: "printas-02",
    url: "https://ritadavis.com.br/images/printas-02.jpg",
    title: "Printas",
    project: "printas",
    description: "",
  },
  {
    id: "printas-03",
    url: "https://ritadavis.com.br/images/printas-03.jpg",
    title: "Printas",
    project: "printas",
    description: "",
  },
  {
    id: "printas-04",
    url: "https://ritadavis.com.br/images/printas-04.jpg",
    title: "Printas",
    project: "printas",
    description: "",
  },

  {
    id: "residencia-01",
    url: "https://ritadavis.com.br/images/residencia-01.jpg",
    title: "Residencia",
    project: "residencia",
    description: "",
  },
  {
    id: "residencia-02",
    url: "https://ritadavis.com.br/images/residencia-02.jpg",
    title: "Residencia",
    project: "residencia",
    description: "",
  },
  {
    id: "residencia-03",
    url: "https://ritadavis.com.br/images/residencia-03.jpg",
    title: "Residencia",
    project: "residencia",
    description: "",
  },
  {
    id: "residencia-04",
    url: "https://ritadavis.com.br/images/residencia-04.jpg",
    title: "Residencia",
    project: "residencia",
    description: "",
  },

  {
    id: "riba-01",
    url: "https://ritadavis.com.br/images/riba-01.jpg",
    title: "Riba",
    project: "riba",
    description: "",
  },
  {
    id: "riba-02",
    url: "https://ritadavis.com.br/images/riba-02.jpg",
    title: "Riba",
    project: "riba",
    description: "",
  },

  {
    id: "solo-01",
    url: "https://ritadavis.com.br/images/solo-01.jpg",
    title: "Solo",
    project: "solo",
    description: "",
  },

  {
    id: "tutarrakk-01",
    url: "https://ritadavis.com.br/images/tutarrakk-01.jpg",
    title: "Tutarrakk",
    project: "tutarrakk",
    description: "",
  },
  {
    id: "tutarrakk-02",
    url: "https://ritadavis.com.br/images/tutarrakk-02.jpg",
    title: "Tutarrakk",
    project: "tutarrakk",
    description: "",
  },
  {
    id: "tutarrakk-03",
    url: "https://ritadavis.com.br/images/tutarrakk-03.jpg",
    title: "Tutarrakk",
    project: "tutarrakk",
    description: "",
  },
  {
    id: "tutarrakk-04",
    url: "https://ritadavis.com.br/images/tutarrakk-04.jpg",
    title: "Tutarrakk",
    project: "tutarrakk",
    description: "",
  },

  {
    id: "voz-01",
    url: "https://ritadavis.com.br/images/voz-01.jpg",
    title: "Voz",
    project: "voz",
    description: "",
  },
  {
    id: "voz-02",
    url: "https://ritadavis.com.br/images/voz-02.jpg",
    title: "Voz",
    project: "voz",
    description: "",
  },
  {
    id: "voz-03",
    url: "https://ritadavis.com.br/images/voz-03.jpg",
    title: "Voz",
    project: "voz",
    description: "",
  },
  {
    id: "voz-04",
    url: "https://ritadavis.com.br/images/voz-04.jpg",
    title: "Voz",
    project: "voz",
    description: "",
  },
];
